### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by Chep2** [tum-gis/3dcitydb-web-map-docker#3]
Hello. Thanks a lot for this tool.
Sorry. Maybe I misunderstood the information from the instructions.
I have installed Ubuntu 18.04 x64 in VirtualBox.
Then I installed Docker and run the command:
docker run -dit --name 3dwebmap-container -p 80:8000 tumgis/3dcitydb-web-map

3D web client starts up:
![1](https://user-images.githubusercontent.com/25004523/116085529-f67ff280-a6af-11eb-9c2b-36084708ca4c.jpg)

But I am unable to run the examples. In both cases, an empty interface without a globe opens:
![2](https://user-images.githubusercontent.com/25004523/116086047-76a65800-a6b0-11eb-97a4-e0559a4fcaa7.jpg)

I noticed that the docker directory is not the same as in the instructions:
![4](https://user-images.githubusercontent.com/25004523/116086115-8756ce00-a6b0-11eb-888f-08d2ad4f9454.jpg)

Help me please.

**Comment by BWibo** [comment]
Thx for reporting this. I'll look into it.
@Son-HNguyen Are the examples generally working with v1.9.0?

**Comment by Son-HNguyen** [comment]
The API access tokens used in these examples were Bing tokens. Since then Cesium has been using Cesium ion tokens. That's the reason why the globe didn't appear in the client as described above. @BWibo please pull `master` to reflect the latest changes to the docker image.

**Comment by Chep2** [comment]
@BWibo, @Son-HNguyen, thanks so much!
I'll be very happy.
This is a very cool software.

**Comment by BWibo** [comment]
@Chep2 
The latest state from of https://github.com/3dcitydb/3dcitydb-web-map `master` is available in the `experimental` tag.
Try using the `tumgis/3dcitydb-web-map:experimental` image. Can you please report if the examples are working with this?

**Comment by Chep2** [comment]
@BWibo, many thanks. I created a new virtual machine, installed Ubuntu and installed experimental docker image.
Now I see the globe. But for some reason I don't see the data.
This screenshot shows an example of "kmlManhattanExample":
![kmlManhattanExample](https://user-images.githubusercontent.com/25004523/126318471-bc7b1b6b-1cd1-446a-8c0d-39ec109861df.jpg)

It's empty here. Is that how it should be?

**Comment by BWibo** [comment]
No, that should not be the case. 
Can you please open the Browser Console (Firefox and Chrome ==> F12) and copy the error msg you should see when refreshing the browser window.

**Comment by Chep2** [comment]
@BWibo, thanks for helping.
I created a new virtual machine.
To install the image, I used the command:
`sudo docker run -dit --name 3dwebmap-container --restart=always -p 80:8000 tumgis/3dcitydb-web-map:experimental`

![Screen1](https://user-images.githubusercontent.com/25004523/126520703-19fabf29-ec8e-48c0-b6d3-e946bbcb300c.jpg)

**Comment by BWibo** [comment]
@Son-HNguyen can you look into this? I think it's not related to the Docker image, but the webclient itself.
This is what I get when I hit the `addDataLayers` button. I assume the examples need to be adapted for the current version of the webclient. 
![err](https://user-images.githubusercontent.com/7643434/126630847-6d592061-1039-46f9-a55d-7d4ec3459b32.png)

**Comment by Son-HNguyen** [comment]
I've updated the scripts for these examples, they should work now. @BWibo please pull the `master` branch and rebuild the Docker image.

**Comment by BWibo** [comment]
@Son-HNguyen Thx for the update. I rebuild and pushed the the images: 

* `tumgis/3dcitydb-web-map:experimental `
* `tumgis/3dcitydb-web-map:alpine-experimental `

@Chep2 Can you please try if this resolves the problems with the examples and report back if it is working?
Make sure to pull the latest version first using: `docker pull IMAGE_NAME`.

**Comment by Chep2** [comment]
@BWibo, @Son-HNguyen, thanks!

For the purity of the experiment, I created a new virtual machine.
I used the new image tumgis/3dcitydb-web-map:experimental

To install, I used the command:
sudo docker run -dit --name 3dwebmap-container --restart=always -p 80:8000 tumgis/3dcitydb-web-map:experimental

I was reinstalling everything, so I didn't use the docker pull command.

![kmlManhattanExample](https://user-images.githubusercontent.com/25004523/128153258-60d512ea-19dc-49c3-bfa7-581672e30fbb.jpg)

**Comment by Son-HNguyen** [comment]
Since the examples are just a small part of the main scripts, not all functions are included, such as the GPS button as you've seen above. Nevertheless, the demos should work without these, here is a screenshot of the KML Manhattan dataset:
![image](https://user-images.githubusercontent.com/5765503/128180829-0ddb9019-6af8-4729-a5fb-d28ef60f25f1.png)

**Comment by BWibo** [comment]
Closing, thx @Son-HNguyen for the fix.
