### ISSUE TITLE
Build error caused by outdated base image

### ISSUE THREAD

**Issue by JulianLeQuack** [tum-gis/3dcitydb-web-map-docker#5]
### Issue Logs
When running `docker build -t tumgis/3dcitydb-web-map .` after cloning the repo, the following error arises:
> 2024/01/11 17:41:27 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 3.5s (6/12)                                                                                  docker:default
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 1.80kB                                                                              0.0s
 => [internal] load metadata for docker.io/library/node:10                                                          2.5s
 => CACHED [1/8] FROM docker.io/library/node:10@sha256:59531d2835edd5161c8f9512f9e095b1836f7a1fcb0ab73e005ec460473  0.0s
 => [internal] load build context                                                                                   0.0s
 => => transferring context: 218B                                                                                   0.0s
 => ERROR [2/8] RUN set -x   && BUILD_PACKAGES='ca-certificates git'   && apt-get update && apt-get install -y --n  1.0s

> [2/8] RUN set -x   && BUILD_PACKAGES='ca-certificates git'   && apt-get update && apt-get install -y --no-install-recommends $BUILD_PACKAGES   && git clone -b "v1.6.0" --depth 1 https://github.com/3dcitydb/3dcitydb-web-map.git /var/www   && cd /var/www   && rm -rf ./.git ./.gitignore ./LICENSE ./README.md ./build.xml      ./node_modules ./server.js $(ls -1 --ignore=ajax-loader.gif --ignore=favicon.png            --ignore=GPS_off.png --ignore=GPS_on.png --ignore=GPS_on_ori.png --ignore=GPS_on_pos_ori.png              ./theme/img)   && mkdir -p /var/www/data   && apt-get purge -y --auto-remove $BUILD_PACKAGES   && rm -rf /var/lib/apt/lists/*:
0.244 + BUILD_PACKAGES=ca-certificates git
0.244 + apt-get update
0.300 Ign:1 http://deb.debian.org/debian stretch InRelease
0.301 Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
0.325 Ign:3 http://deb.debian.org/debian stretch-updates InRelease
0.326 Ign:4 http://security.debian.org/debian-security stretch/updates Release
0.349 Ign:5 http://deb.debian.org/debian stretch Release
0.360 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.371 Ign:7 http://deb.debian.org/debian stretch-updates Release
0.383 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.394 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.405 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.414 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.424 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.434 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.446 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.453 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.471 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.474 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.497 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.499 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.526 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.527 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.548 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.552 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.571 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.575 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.595 Err:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.595   404  Not Found
0.597 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.619 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.624 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.647 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.671 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.695 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.720 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.740 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.761 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.783 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.821 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.844 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.868 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.893 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.893   404  Not Found
0.925 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
0.959 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.959   404  Not Found
0.961 Reading package lists...
0.967 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
0.967 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
0.967 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
0.967 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
0.967 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found

>  22 | >>>   && cd /var/www \
  23 | >>>   && rm -rf ./.git ./.gitignore ./LICENSE ./README.md ./build.xml \
  24 | >>>      ./node_modules ./server.js $(ls -1 --ignore=ajax-loader.gif --ignore=favicon.png \        
  25 | >>>              --ignore=GPS_off.png --ignore=GPS_on.png --ignore=GPS_on_ori.png --ignore=GPS_on_pos_ori.png \
  26 | >>>               ./theme/img) \
  27 | >>>   && mkdir -p /var/www/data \
  28 | >>>   && apt-get purge -y --auto-remove $BUILD_PACKAGES \
  29 | >>>   && rm -rf /var/lib/apt/lists/*
gnore=GPS_on_pos_ori.png \t\t ./theme/img)   && mkdir -p /var/www/data   && apt-get purge -y --auto-remove $BUILD_PACKAGES   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
gnore=GPS_on_pos_ori.png \t\t ./theme/img)   && mkdir -p /var/www/data   && apt-get purge -y --auto-remove $BUILD_PACKAGES   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

### Docker Version
> Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:44 2023
 OS/Arch:           windows/amd64
 Context:           default

> Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Side Notes
- When running `docker build -t tumgis/3dcitydb-web-map .` inside /alpine, I do not get an error message and the image runs as expected.
- I cannot use the alpine sub-version though, as I need the newer version for my thematic data source (using PostgREST).

Thank you for your help!

**Comment by BWibo** [comment]
Hey there, this was cased by the outdated `node` version this image was using.
Ich updated `Dockerfile` and `alpine/Dockerfile` to `node` v21 and some packages too. The build should now work again.

However, we should migrate this to the official 3DCityDB Web Map Client repo. But this is a separate issue.
@JulianLeQuack Can you please test this an confirm here if it is working?

**Comment by BWibo** [comment]
Resolved in 970ecff, d719233

**Comment by JulianLeQuack** [comment]
> Hey there, this was cased by the outdated `node` version this image was using. Ich updated `Dockerfile` and `alpine/Dockerfile` to `node` v21 and some packages too. The build should now work again.
> 
> However, we should migrate this to the official 3DCityDB Web Map Client repo. But this is a separate issue. @JulianLeQuack Can you please test this an confirm here if it is working?

Hi! Yes, it works now, thank you!
